[package]
name = "FAI"
version = "1.0.2"

[addresses]
StarcoinFramework = "0x1"
FaiAdmin = "0x4FFCC98F43ce74668264a0CF6Eebe42b"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="01c84198819310620f2417413c3c800df8292ae5"}

